language: python

install:
- pip install -U platformio

env:
- PLATFORMIO_CI_SRC=examples/CommandSniffer
- PLATFORMIO_CI_SRC=examples/DataLogger
- PLATFORMIO_CI_SRC=examples/LapCounter
- PLATFORMIO_CI_SRC=examples/StartLight

script:
- platformio ci --lib="src" --board=nucleo_f446re -O framework=mbed
- platformio ci --lib="src" --board=pico -O framework=arduino
- platformio ci --lib="src" --board=uno
