language: python

sudo: false

cache:
  directories:
    - "~/.platformio"
    - $HOME/.cache/pip

env:
- PLATFORMIO_CI_SRC=examples/CommandSniffer
- PLATFORMIO_CI_SRC=examples/DataLogger
- PLATFORMIO_CI_SRC=examples/LapCounter
- PLATFORMIO_CI_SRC=examples/StartLight

install:
- pip install -U platformio
- pio update

script:
- pio ci --lib="src" --board=nucleo_f446re -O framework=mbed
- pio ci --lib="src" --board=pico -O framework=arduino
- pio ci --lib="src" --board=uno
